// Generated by CIRCT firtool-1.76.0
module Queue16_UInt8(
  input  clock,
         reset,
  output io_enq_ready,
  input  io_enq_valid
);

  reg  [3:0] enq_ptr_value;
  reg  [3:0] deq_ptr_value;
  reg        maybe_full;
  wire       ptr_match = enq_ptr_value == deq_ptr_value;
  wire       empty = ptr_match & ~maybe_full;
  wire       full = ptr_match & maybe_full;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 4'h0;
      deq_ptr_value <= 4'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_enq;
      do_enq = ~full & io_enq_valid;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value + 4'h1;
      if (~empty)
        deq_ptr_value <= deq_ptr_value + 4'h1;
      if (~(do_enq == ~empty))
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  assign io_enq_ready = ~full;
endmodule

module MyFIFO(
  input  clock,
         reset,
  output io_enq_ready,
  input  io_enq_valid
);

  Queue16_UInt8 quque (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (io_enq_ready),
    .io_enq_valid (io_enq_valid)
  );
endmodule

module DecoupledDriver(
  input  clock,
         reset,
         io_out_ready,
  output io_out_valid,
  input  io_en,
  output io_done
);

  reg [2:0] idx;
  reg       doneReg;
  always @(posedge clock) begin
    if (reset) begin
      idx <= 3'h0;
      doneReg <= 1'h0;
    end
    else begin
      automatic logic _GEN = io_out_ready & io_en;
      automatic logic _GEN_0 = idx == 3'h3;
      if (~_GEN | _GEN_0) begin
      end
      else
        idx <= idx + 3'h1;
      doneReg <= _GEN & _GEN_0 | doneReg;
    end
  end // always @(posedge)
  assign io_out_valid = io_en;
  assign io_done = doneReg;
endmodule

module MyFIFOHWTestTop(
  input  clock,
         reset,
  output io_done,
  input  io_en
);

  wire _driver_io_out_valid;
  wire _target_io_enq_ready;
  MyFIFO target (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_target_io_enq_ready),
    .io_enq_valid (_driver_io_out_valid)
  );
  DecoupledDriver driver (
    .clock        (clock),
    .reset        (reset),
    .io_out_ready (_target_io_enq_ready),
    .io_out_valid (_driver_io_out_valid),
    .io_en        (io_en),
    .io_done      (io_done)
  );
endmodule

